name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    
    - name: make
      run: make
      working-directory: ${{env.GITHUB_WORKSPACE}}/gcc-build

    - name: Push build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: voidsprite-build-linux
        path: |
          gcc-build/build
